AWSTemplateFormatVersion: "2010-09-09"
Description: Gives GitHubActionsDeployRole access to create S3 buckets

Resources:
  S3TemplateAccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      # A name for this specific "tool" you're adding
      PolicyName: CrossAccountAccess
      # The name of the role that already exists in the account
      Roles:
        - GitHubActionsDeployRole 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
              - "organizations:*"
            Resource: "*"
          - Effect: Allow
            Action: 
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam:::role/CrossAccountDeployRole"


