AWSTemplateFormatVersion: "2010-09-09"
Description: Creates S3 Bucket that stores the CrossAccountDeployRole 

Resources:
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CrossAccountS3TemplateRole"
      Policies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:*"
            Resource: "*"
