AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an S3 bucket.
Resources:
  ClientS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "scootshare-website-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  AssetsS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "scootshare-website-${AWS::AccountId}-assets"

  ClientS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ClientS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal: "*"
            Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
              - !Sub "${ClientS3Bucket.Arn}/*"
            Condition:
              IpAddress:
                'aws:SourceIp': ['99.237.197.41']

 #Creates a new origin access control in CloudFront. After you create an origin access control, 
  #you can add it to an origin in a CloudFront distribution so that CloudFront sends authenticated (signed) requests to the origin.
  AssetsS3BucketCloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: scootshare-assets-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Cache Policy for CloudFront
        Name: scootshare-assets-cdn-cache-policy
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 86400
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: all
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt AssetsS3Bucket.RegionalDomainName
            OriginAccessControlId: !GetAtt AssetsS3BucketCloudFrontOAC.Id
            S3OriginConfig: {}  # Empty for OAC
        DefaultCacheBehavior:
          AllowedMethods: ['GET', 'HEAD']
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: allow-all
          CachePolicyId: !Ref CloudFrontCachePolicy
  
  AssetsS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref AssetsS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal:
              Service: cloudfront.amazonaws.com
            Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
              - !Sub "${AssetsS3Bucket.Arn}/*"
            Condition:
              ArnLike:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'


Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref AssetsS3Bucket # Use !Ref to get the physical name of the bucket
  
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront distribution domain
   