AWSTemplateFormatVersion: "2010-09-09"
Description: Creates S3 Bucket that stores the CrossAccountDeployRole 

Resources:
  S3CreateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: deployment-template

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3CreateBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal:
              Service: 'cloudformation.amazon.com'
            Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
              - !Sub "${S3CreateBucket.Arn}/*"
            Condition:
              StringEquals:
                "aws:PrincipalOrgID": "o-ygk30uswcu"
