AWSTemplateFormatVersion: "2010-09-09"
Description: Creates S3 Bucket that stores the CrossAccountDeployRole 

Resources:
  S3CreateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: deployment-template
